## -------------------------------------------------------------------------
## Appendix: Evaluation of pointwise interval coverage
##
## This script reproduces the simulation study reported in the appendix of
## the manuscript. The study is based on the nonlinear one-dimensional
## probability function used in Example 2.
##
## Three methods are compared:
##
##   1. Standard BKP without effective-sample-size calibration
##      (ess = "none").
##
##   2. BKP with Shepard effective-sample-size calibration
##      (ess = "shepard").
##
##   3. A logistic Gaussian process (LGP) model fitted using gplite.
##
## For each simulated dataset, pointwise 95% intervals are evaluated in two
## ways:
##
##   - at a fixed dense grid of 2,000 input locations;
##   - at the randomly generated training locations.
##
## The coverage rate is the proportion of evaluation locations at which the
## interval contains the true probability function. For each sample size and
## method, the script reports the mean and standard deviation of the coverage
## rates across repeated simulated datasets.
##
## The script also produces a six-panel figure showing posterior means and
## pointwise 95% intervals from one representative simulated dataset for each
## sample size and method.
##
## All paths are relative to the repository root.
##
## Outputs:
##
##   code/figure/ex2_combined.pdf
##   code/result/coverage_summary.csv
## -------------------------------------------------------------------------


## -------------------------------------------------------------------------
## Required packages
## -------------------------------------------------------------------------

## BKP provides the standard and ESS-calibrated Beta Kernel Process methods.
## gplite provides the logistic Gaussian process comparison model.
## tgp provides Latin hypercube sampling through lhs().
library(BKP)
library(gplite)
library(tgp)


## Set console formatting options so that printed output follows the style
## used in the manuscript's R code examples.
options(
  prompt = "R> ",
  continue = "+  ",
  width = 70,
  useFancyQuotes = FALSE
)


## Create output directories so that this script can be run independently
## from a clean clone of the repository.
dir.create(
  "code/figure",
  recursive = TRUE,
  showWarnings = FALSE
)

dir.create(
  "code/result",
  recursive = TRUE,
  showWarnings = FALSE
)


## -------------------------------------------------------------------------
## Simulation settings
## -------------------------------------------------------------------------

## Number of independently simulated datasets for each sample-size setting.
##
## This value must agree with the number of replications reported in the
## manuscript appendix and in the caption of the coverage table.
n_reps <- 100

## Number of equally spaced locations in the fixed evaluation grid.
n_grid <- 2000

## Nominal pointwise credible-interval level.
ci_level <- 0.95

## Lower and upper tail probabilities used by gplite.
alpha_ci <- (1 - ci_level) / 2

## Training sample sizes considered in the simulation study.
n_train_values <- c(30, 100)


## Set the random seed so that the representative datasets and all simulation
## replications are reproducible.
set.seed(123)


## -------------------------------------------------------------------------
## Example 2 probability function and data-generating mechanism
## -------------------------------------------------------------------------

## Define the one-dimensional input domain.
Xbounds <- matrix(
  c(-2, 2),
  nrow = 1
)


## Define the nonlinear probability function from Example 2:
##
## pi(x) =
##   {1 + exp(-x^2) cos[10(1 - exp(-x))/(1 + exp(-x))]} / 2.
##
## The function accepts either a numeric vector or a one-column matrix.
true_pi_fun <- function(x) {
  x <- as.numeric(x)
  
  (
    1 +
      exp(-x^2) *
      cos(
        10 *
          (1 - exp(-x)) /
          (1 + exp(-x))
      )
  ) / 2
}


## Generate one simulated binomial dataset.
##
## Input locations are generated by Latin hypercube sampling. The trial size
## at each location is sampled from 1, ..., 100, and the number of successes is
## generated from the corresponding binomial distribution.
generate_data <- function(n, Xbounds) {
  X <- lhs(
    n = n,
    rect = Xbounds
  )
  
  probability <- true_pi_fun(X)
  
  trials <- sample(
    100,
    n,
    replace = TRUE
  )
  
  successes <- rbinom(
    n,
    size = trials,
    prob = probability
  )
  
  list(
    X = X,
    y = successes,
    m = trials
  )
}


## -------------------------------------------------------------------------
## Coverage-rate calculation
## -------------------------------------------------------------------------

## Compute the proportion of locations at which the pointwise interval
## [lower, upper] contains the true probability value.
compute_coverage <- function(lower, upper, truth) {
  mean(
    truth >= lower & truth <= upper,
    na.rm = TRUE
  )
}


## Summarize coverage rates across simulation replications.
summarize_coverage <- function(x) {
  c(
    mean = mean(
      x,
      na.rm = TRUE
    ),
    sd = sd(
      x,
      na.rm = TRUE
    )
  )
}


## Print one coverage summary in percentage form.
print_coverage <- function(label, summary_value) {
  cat(
    sprintf(
      "  %-16s  %5.1f%% (SD = %4.1f)\n",
      label,
      100 * summary_value["mean"],
      100 * summary_value["sd"]
    )
  )
}


## -------------------------------------------------------------------------
## Fixed evaluation grid
## -------------------------------------------------------------------------

## Construct an equally spaced grid over the full input domain. The same grid
## is used for every simulated dataset, so this evaluation is referred to as
## the fixed-grid evaluation rather than a test-set evaluation.
X_grid <- matrix(
  seq(
    Xbounds[1, 1],
    Xbounds[1, 2],
    length.out = n_grid
  ),
  ncol = 1
)

true_pi_grid <- true_pi_fun(
  X_grid
)


## -------------------------------------------------------------------------
## Result containers
## -------------------------------------------------------------------------

## Store simulation summaries for each sample-size configuration.
results <- list()

## Store representative fitted curves for the six-panel appendix figure.
plot_predictions <- list()

## Method labels and corresponding list keys used in the plotting loop.
plot_methods <- c(
  "BKP",
  "BKP-ESS",
  "LGP"
)

## Store table-ready results for export to CSV.
summary_rows <- list()
summary_index <- 1L


## -------------------------------------------------------------------------
## Simulation loop over training sample sizes
## -------------------------------------------------------------------------

for (n_train in n_train_values) {
  config_name <- sprintf(
    "Example 2, n=%d",
    n_train
  )
  
  cat("\n============================================================\n")
  cat(
    sprintf(
      "Sample size n = %d\n",
      n_train
    )
  )
  cat("============================================================\n\n")
  
  
  ## -----------------------------------------------------------------------
  ## Representative dataset for the appendix figure
  ## -----------------------------------------------------------------------
  
  cat("  Fitting methods for the appendix figure ...\n")
  
  plot_data <- generate_data(
    n_train,
    Xbounds
  )
  
  
  ## Fit the standard BKP model using the noninformative beta prior and no
  ## effective-sample-size calibration.
  fit_bkp_plot <- fit_BKP(
    plot_data$X,
    plot_data$y,
    plot_data$m,
    Xbounds = Xbounds,
    prior = "noninformative",
    loss = "brier",
    ess = "none"
  )
  
  
  ## Fit BKP with Shepard effective-sample-size calibration.
  fit_ess_plot <- fit_BKP(
    plot_data$X,
    plot_data$y,
    plot_data$m,
    Xbounds = Xbounds,
    prior = "noninformative",
    loss = "brier",
    ess = "shepard"
  )
  
  
  ## Fit the logistic Gaussian process comparison model using a binomial
  ## likelihood and the location-specific trial sizes.
  fit_lgp_plot <- gp_init(
    cf = cf_sexp(),
    lik = lik_binomial()
  )
  
  fit_lgp_plot <- suppressWarnings(
    gp_optim(
      fit_lgp_plot,
      plot_data$X,
      plot_data$y,
      trials = plot_data$m,
      verbose = FALSE
    )
  )
  
  
  ## Obtain pointwise posterior summaries over the fixed evaluation grid.
  pred_bkp_plot <- predict(
    fit_bkp_plot,
    Xnew = X_grid,
    CI_level = ci_level
  )
  
  pred_ess_plot <- predict(
    fit_ess_plot,
    Xnew = X_grid,
    CI_level = ci_level
  )
  
  pred_lgp_plot <- gp_pred(
    fit_lgp_plot,
    X_grid,
    quantiles = c(
      alpha_ci,
      1 - alpha_ci
    ),
    transform = TRUE
  )
  
  
  ## Store observed proportions and fitted interval summaries for the
  ## representative six-panel figure.
  observed_proportions <- plot_data$y / plot_data$m
  
  plot_predictions[[config_name]] <- list(
    X = plot_data$X,
    observed = observed_proportions,
    bkp = list(
      mean = as.vector(pred_bkp_plot$mean),
      lower = as.vector(pred_bkp_plot$lower),
      upper = as.vector(pred_bkp_plot$upper)
    ),
    bkp_ess = list(
      mean = as.vector(pred_ess_plot$mean),
      lower = as.vector(pred_ess_plot$lower),
      upper = as.vector(pred_ess_plot$upper)
    ),
    lgp = list(
      mean = as.vector(pred_lgp_plot$mean),
      lower = as.vector(pred_lgp_plot$quantiles[, 1]),
      upper = as.vector(pred_lgp_plot$quantiles[, 2])
    )
  )
  
  
  ## -----------------------------------------------------------------------
  ## Repeated coverage experiment
  ## -----------------------------------------------------------------------
  
  cat(
    sprintf(
      "  Running %d simulation replications ...\n",
      n_reps
    )
  )
  
  
  ## Allocate vectors for fixed-grid and training-location coverage rates.
  bkp_grid_coverage <- numeric(n_reps)
  bkp_train_coverage <- numeric(n_reps)
  
  ess_grid_coverage <- numeric(n_reps)
  ess_train_coverage <- numeric(n_reps)
  
  lgp_grid_coverage <- numeric(n_reps)
  lgp_train_coverage <- numeric(n_reps)
  
  
  for (replication in seq_len(n_reps)) {
    simulated_data <- generate_data(
      n_train,
      Xbounds
    )
    
    true_pi_train <- true_pi_fun(
      simulated_data$X
    )
    
    
    ## ---------------------------------------------------------------------
    ## Standard BKP
    ## ---------------------------------------------------------------------
    
    fit_bkp <- fit_BKP(
      simulated_data$X,
      simulated_data$y,
      simulated_data$m,
      Xbounds = Xbounds,
      prior = "noninformative",
      loss = "brier",
      ess = "none"
    )
    
    pred_bkp_grid <- predict(
      fit_bkp,
      Xnew = X_grid,
      CI_level = ci_level
    )
    
    pred_bkp_train <- predict(
      fit_bkp,
      Xnew = NULL,
      CI_level = ci_level
    )
    
    bkp_grid_coverage[replication] <- compute_coverage(
      pred_bkp_grid$lower,
      pred_bkp_grid$upper,
      true_pi_grid
    )
    
    bkp_train_coverage[replication] <- compute_coverage(
      pred_bkp_train$lower,
      pred_bkp_train$upper,
      true_pi_train
    )
    
    
    ## ---------------------------------------------------------------------
    ## BKP with Shepard ESS calibration
    ## ---------------------------------------------------------------------
    
    fit_ess <- fit_BKP(
      simulated_data$X,
      simulated_data$y,
      simulated_data$m,
      Xbounds = Xbounds,
      prior = "noninformative",
      loss = "brier",
      ess = "shepard"
    )
    
    pred_ess_grid <- predict(
      fit_ess,
      Xnew = X_grid,
      CI_level = ci_level
    )
    
    pred_ess_train <- predict(
      fit_ess,
      Xnew = NULL,
      CI_level = ci_level
    )
    
    ess_grid_coverage[replication] <- compute_coverage(
      pred_ess_grid$lower,
      pred_ess_grid$upper,
      true_pi_grid
    )
    
    ess_train_coverage[replication] <- compute_coverage(
      pred_ess_train$lower,
      pred_ess_train$upper,
      true_pi_train
    )
    
    
    ## ---------------------------------------------------------------------
    ## Logistic Gaussian process
    ## ---------------------------------------------------------------------
    
    fit_lgp <- gp_init(
      cf = cf_sexp(),
      lik = lik_binomial()
    )
    
    fit_lgp <- suppressWarnings(
      gp_optim(
        fit_lgp,
        simulated_data$X,
        simulated_data$y,
        trials = simulated_data$m,
        verbose = FALSE
      )
    )
    
    pred_lgp_grid <- gp_pred(
      fit_lgp,
      X_grid,
      quantiles = c(
        alpha_ci,
        1 - alpha_ci
      ),
      transform = TRUE
    )
    
    pred_lgp_train <- gp_pred(
      fit_lgp,
      simulated_data$X,
      quantiles = c(
        alpha_ci,
        1 - alpha_ci
      ),
      transform = TRUE
    )
    
    lgp_grid_coverage[replication] <- compute_coverage(
      pred_lgp_grid$quantiles[, 1],
      pred_lgp_grid$quantiles[, 2],
      true_pi_grid
    )
    
    lgp_train_coverage[replication] <- compute_coverage(
      pred_lgp_train$quantiles[, 1],
      pred_lgp_train$quantiles[, 2],
      true_pi_train
    )
  }
  
  
  ## -----------------------------------------------------------------------
  ## Summarize coverage across replications
  ## -----------------------------------------------------------------------
  
  grid_bkp_summary <- summarize_coverage(
    bkp_grid_coverage
  )
  
  grid_ess_summary <- summarize_coverage(
    ess_grid_coverage
  )
  
  grid_lgp_summary <- summarize_coverage(
    lgp_grid_coverage
  )
  
  train_bkp_summary <- summarize_coverage(
    bkp_train_coverage
  )
  
  train_ess_summary <- summarize_coverage(
    ess_train_coverage
  )
  
  train_lgp_summary <- summarize_coverage(
    lgp_train_coverage
  )
  
  
  ## Print sample-size-specific results.
  cat("\n  --- Fixed grid ---\n")
  print_coverage(
    "BKP",
    grid_bkp_summary
  )
  print_coverage(
    "BKP-ESS",
    grid_ess_summary
  )
  print_coverage(
    "LGP",
    grid_lgp_summary
  )
  
  cat("\n  --- Training locations ---\n")
  print_coverage(
    "BKP",
    train_bkp_summary
  )
  print_coverage(
    "BKP-ESS",
    train_ess_summary
  )
  print_coverage(
    "LGP",
    train_lgp_summary
  )
  
  
  ## Store summaries for later printing and CSV export.
  results[[config_name]] <- list(
    n = n_train,
    fixed_grid_bkp = grid_bkp_summary,
    fixed_grid_ess = grid_ess_summary,
    fixed_grid_lgp = grid_lgp_summary,
    training_bkp = train_bkp_summary,
    training_ess = train_ess_summary,
    training_lgp = train_lgp_summary
  )
  
  
  ## Add table-ready rows for the fixed-grid evaluation.
  for (method_name in c("BKP", "BKP-ESS", "LGP")) {
    method_summary <- switch(
      method_name,
      "BKP" = grid_bkp_summary,
      "BKP-ESS" = grid_ess_summary,
      "LGP" = grid_lgp_summary
    )
    
    summary_rows[[summary_index]] <- data.frame(
      evaluation = "Fixed grid",
      n = n_train,
      method = method_name,
      mean_coverage = unname(method_summary["mean"]),
      sd_coverage = unname(method_summary["sd"]),
      nominal_level = ci_level,
      n_replications = n_reps,
      n_evaluation_points = n_grid
    )
    
    summary_index <- summary_index + 1L
  }
  
  
  ## Add table-ready rows for the training-location evaluation.
  for (method_name in c("BKP", "BKP-ESS", "LGP")) {
    method_summary <- switch(
      method_name,
      "BKP" = train_bkp_summary,
      "BKP-ESS" = train_ess_summary,
      "LGP" = train_lgp_summary
    )
    
    summary_rows[[summary_index]] <- data.frame(
      evaluation = "Training locations",
      n = n_train,
      method = method_name,
      mean_coverage = unname(method_summary["mean"]),
      sd_coverage = unname(method_summary["sd"]),
      nominal_level = ci_level,
      n_replications = n_reps,
      n_evaluation_points = n_train
    )
    
    summary_index <- summary_index + 1L
  }
}


## -------------------------------------------------------------------------
## Six-panel appendix figure
## -------------------------------------------------------------------------

## The rows correspond to BKP, BKP-ESS, and LGP.
## The columns correspond to n = 30 and n = 100.
pdf(
  "code/figure/ex2_combined.pdf",
  width = 8,
  height = 12
)

par(
  mfrow = c(3, 2),
  mar = c(4, 4, 3, 1)
)

panel_labels <- c(
  "(a)",
  "(b)",
  "(c)",
  "(d)",
  "(e)",
  "(f)"
)

panel_index <- 1L


for (method_index in seq_along(plot_methods)) {
  method_name <- plot_methods[method_index]
  
  prediction_key <- switch(
    as.character(method_index),
    "1" = "bkp",
    "2" = "bkp_ess",
    "3" = "lgp"
  )
  
  for (n_train in n_train_values) {
    config_name <- sprintf(
      "Example 2, n=%d",
      n_train
    )
    
    plot_data <- plot_predictions[[config_name]]
    
    posterior_mean <- plot_data[[prediction_key]]$mean
    lower <- plot_data[[prediction_key]]$lower
    upper <- plot_data[[prediction_key]]$upper
    observed <- plot_data$observed
    
    ## Expand the vertical plotting range slightly while respecting the
    ## probability bounds [0, 1].
    y_limits <- c(
      max(
        0,
        min(
          c(
            lower,
            observed
          )
        ) * 0.9
      ),
      min(
        1,
        max(
          c(
            upper,
            observed
          )
        ) * 1.1
      )
    )
    
    plot(
      X_grid,
      posterior_mean,
      type = "n",
      xlab = "x",
      ylab = "Probability",
      main = sprintf(
        "%s %s, n=%d",
        panel_labels[panel_index],
        method_name,
        n_train
      ),
      ylim = y_limits
    )
    
    ## Draw the pointwise 95% interval band.
    polygon(
      c(
        X_grid,
        rev(X_grid)
      ),
      c(
        lower,
        rev(upper)
      ),
      col = "lightgrey",
      border = NA
    )
    
    ## Add the posterior mean, observed proportions, and true probability.
    lines(
      X_grid,
      posterior_mean,
      col = "blue",
      lwd = 2
    )
    
    points(
      plot_data$X,
      observed,
      pch = 20,
      col = "red"
    )
    
    lines(
      X_grid,
      true_pi_grid,
      col = "black",
      lwd = 2
    )
    
    legend(
      "topleft",
      bty = "n",
      cex = 1,
      legend = c(
        "Estimated Probability",
        "95% Pointwise Interval",
        "Observed Proportions",
        "True Probability"
      ),
      col = c(
        "blue",
        "lightgrey",
        "red",
        "black"
      ),
      lwd = c(
        2,
        8,
        NA,
        2
      ),
      pch = c(
        NA,
        NA,
        20,
        NA
      ),
      lty = c(
        1,
        1,
        NA,
        1
      )
    )
    
    panel_index <- panel_index + 1L
  }
}

dev.off()

cat(
  "\nCombined figure saved to code/figure/ex2_combined.pdf\n"
)


## -------------------------------------------------------------------------
## Export coverage summary
## -------------------------------------------------------------------------

coverage_summary <- do.call(
  rbind,
  summary_rows
)

write.csv(
  coverage_summary,
  "code/result/coverage_summary.csv",
  row.names = FALSE
)

cat(
  "Coverage summary saved to code/result/coverage_summary.csv\n"
)


## -------------------------------------------------------------------------
## Console summary
## -------------------------------------------------------------------------

cat("\n================================================================\n")
cat("Summary: Pointwise interval coverage (nominal 95%)\n")
cat("Example 2: one-dimensional oscillating probability function\n")
cat("================================================================\n\n")


for (evaluation_name in c(
  "Fixed grid",
  "Training locations"
)) {
  cat(
    sprintf(
      "--- %s ---\n",
      evaluation_name
    )
  )
  
  for (config_name in names(results)) {
    result <- results[[config_name]]
    
    cat(
      sprintf(
        "\n  %s\n",
        config_name
      )
    )
    
    if (evaluation_name == "Fixed grid") {
      print_coverage(
        "BKP",
        result$fixed_grid_bkp
      )
      print_coverage(
        "BKP-ESS",
        result$fixed_grid_ess
      )
      print_coverage(
        "LGP",
        result$fixed_grid_lgp
      )
    } else {
      print_coverage(
        "BKP",
        result$training_bkp
      )
      print_coverage(
        "BKP-ESS",
        result$training_ess
      )
      print_coverage(
        "LGP",
        result$training_lgp
      )
    }
  }
  
  cat("\n")
}

cat("================================================================\n")
cat("Analysis complete.\n")